### PR TITLE
[EASI-4301] Make the Navigation Sticky

### PR DESCRIPTION
**Pull request by garyjzhao**
# EASI-4301

## Changes and Description

- Deleted unused `HeaderWrapper` component --- to remove bloat
- Adjusted `index.scss` to better match what is needed 
- Updated test to better reflect the actual component
- Shifted the header components around to make the sticky nav to work 
    - Added comments to help future development work
- `src/components/NavigationBar/index.scss` was mainly prettier formatting update
- Updated props for `NavigationBar` component
- Added `z-top` style class for the `SkipNav` component

## How to test this change

1. Check the functionality and stickiness works for both desktop size and mobile size for the following pages:
    1. Landing Page
    2. Get Access page
    3. Sign in Page
    4. NDA page
    5. rest of the Logged in pages
   
  

## PR Author Review Checklist

- [ ] Met the ticket's acceptance criteria, or will meet them in a subsequent PR.
- [ ] Added or updated tests for backend resolvers or other functions as needed.
- [ ] Added or updated client tests for new components, parent components, functions, or e2e tests as necessary.
- [ ] Updated the [Postman Collection](../MINT.postman_collection.json) if necessary.

## PR Reviewer Guidelines
- It's best to pull the branch locally and test it, rather than just looking at the code online!
- Check that all code is adequately covered by tests - if it isn't feel free to suggest the addition of tests.
- Always make comments, even if it's minor, or if you don't understand why something was done.

### CODE REVIEW

**Review by patrickseguraoddball — DISMISSED** [review]
Nice work Gary works really great.  I think the only thing that we might want to revisit/ clarification - is the menu sticky and readonly filter sticky supposed to stack?  It works great as is but might be a question to bring to UX.  Works as intended in the ticket AC though so a good to go from me!

**Comment by garyjzhao** [comment]
@patrickseguraoddball I remember that Natasha or Zoe mentioned that it should stack, so I updated the code to do the double stack. Please have a review.

**Comment by patrickseguraoddball** [comment]
Also still getting a bit of pixel discrepancy when changing nav sections.  It doesnt quite line up/ a small scroll still occurs before side nave becomes fixed

**Review by patrickseguraoddball — CHANGES_REQUESTED** [review]
Getting some weird snapping behavior after I click on Beneficiaries, then any other section.  It doesn't snap to the normal position.

Screenshot 2024-05-29 at 12 25 43 PM

Screenshot 2024-05-29 at 12 25 56 PM

**Review by patrickseguraoddball — APPROVED** [review]
Nice!

**Pull request merged**
