### PR TITLE
Easi 2069/note field updates

### PR DESCRIPTION
**Pull request by patrickseguraoddball**
# EASI-2069

## Changes and Description

[EASI-2069](https://jiraent.cms.gov/browse/EASI-2069)

- Updated the <AddNote /> component to auto expand if value exists
- Added unit test

Small side fixes
- Fixed a typo on `coordinateWorkNote`
- Added index to collaborator combobox to allow for accessible navigation

[Slack thread about this](https://oddball.slack.com/archives/C030RBZMTRA/p1653597229971309)

Screen Shot 2022-07-22 at 9 19 46 AM

## Notes

- Utilized a Formik hook to fetch field value from name
- This allowed there to be no changes in implementation, only directly in existing component definition

## How to test this change

- Create a model plan or use a seeded plan
- Note field with no text should be collapsed on page load - `Add an additional note`
- Note field with text should automatically expand on load with `Add an additional note` hidden
- Deleting a note should leave the text area expanded until saved - on next load will be collapsed

## PR Author Review Checklist

- [ ] Met the ticket's acceptance criteria, or will meet them in a subsequent PR.
- [ ] Added or updated tests for backend resolvers or other functions as needed.
- [ ] Added or updated client tests for new components, parent components, functions, or e2e tests as necessary.
- [ ] Tested user-facing changes with voice-over and the [rotor menu](https://support.apple.com/guide/voiceover/with-the-voiceover-rotor-mchlp2719/mac)

## PR Reviewer Guidelines
- It's best to pull the branch locally and test it, rather than just looking at the code online!
- Check that all code is adequately covered by tests - if it isn't feel free to suggest the addition of tests.
- Always make comments, even if it's minor, or if you don't understand why something was done.

### CODE REVIEW

**Review by StevenWadeOddball — DISMISSED** [review]
When I tested this, I saw one field that didn't expanded even though there is a note present (This is PM Butler on the plan basics page).

image

Everywhere else I looked it seemed to be working! This will be great! Thanks Patrick!

**Review by garyjzhao — CHANGES_REQUESTED** [review]
Type Check error showing that `euaUserId` should be `euaUserID` (capital ID) in `src/views/ModelPlan/Collaborators/AddCollaborator/index.tsx` line 202.

IDK why i cant comment directly on that file.

**Comment by patrickseguraoddball** [comment]
> Type Check error showing that `euaUserId` should be `euaUserID` (capital ID) in `src/views/ModelPlan/Collaborators/AddCollaborator/index.tsx` line 202.
> 
> IDK why i cant comment directly on that file.

Yeah I had seen that warning, although it is definitely not correct.  It should not be `euaUserID`.  Both are throwing errors.  I'll take another look

**Review by garyjzhao — APPROVED** [review]
Slacked with @patrickseguraoddball to clarify that the type check is not a blocker on this particular PR. 
The functionality and code looks good to me.

**Pull request merged**
