### PR TITLE
[EASI-2630] EUA showing on timestamp instead of user name

### PR DESCRIPTION
**Pull request by garyjzhao**
# EASI-2630

## Changes and Description

- Quick pairing with @StevenWadeOddball  to make sure basics' `ready_for_review_by` and `ready_for_review_dts` gets updated
- `GetUserInfo` query and type
- Add `GetUserInfo` queries to render username instead of EUA ID
- Change `itTools` to `itSolutions` in Prepare for Clearance checklist

### Checking user name is rendering in the `Ready for Review` section

1. Make a Task List section as ready for review.
2. Return to page and make sure the text is rendering username 

### Checking user name is rendering in `Prepare for Clearance` section

1. Go through the task list to enable the `Prepare for Clearance` section
2. Mark the sections ready for clearance
3. Verify that the timestamp shows username, not eua id

## PR Author Review Checklist

- [ ] Met the ticket's acceptance criteria, or will meet them in a subsequent PR.
- [ ] Added or updated tests for backend resolvers or other functions as needed.
- [ ] Added or updated client tests for new components, parent components, functions, or e2e tests as necessary.
- [ ] Updated the [Postman Collection](../MINT.postman_collection.json) if necessary.

## PR Reviewer Guidelines
- It's best to pull the branch locally and test it, rather than just looking at the code online!
- Check that all code is adequately covered by tests - if it isn't feel free to suggest the addition of tests.
- Always make comments, even if it's minor, or if you don't understand why something was done.

### CODE REVIEW

**Review by StevenWadeOddball — APPROVED** [review]
Thanks Gary, I'm approving the BE piece. I also ran this locally and it worked according the test script!

**Review by patrickseguraoddball — CHANGES_REQUESTED** [review]
When I check `Ready for Review` and click to save and go to next section, then immediately go back.  The box is still checked, but the name and date are missing.

Screenshot 2023-02-02 at 10 15 44 AM

**Comment by patrickseguraoddball** [comment]
I'm also not seeing the names rendered in Prepare for Clearance section

**Review by patrickseguraoddball — APPROVED** [review]
LG Thanks Gary!

**Pull request merged**
