### PR TITLE
[EASI-4012] GQL Modularization - Plan Participants and Providers

### PR DESCRIPTION
**Pull request by OddTomBrooks**
# EASI-4012

## Changes and Description

- Extracted GQL from main schema to separate module

## How to test this change

- Assert that the application builds and runs as expected with no observable changes to execution

## PR Author Review Checklist

- [x] Met the ticket's acceptance criteria, or will meet them in a subsequent PR.
- [ ] Added or updated tests for backend resolvers or other functions as needed.
- [ ] Added or updated client tests for new components, parent components, functions, or e2e tests as necessary.
- [ ] Updated the [Postman Collection](../MINT.postman_collection.json) if necessary.

## PR Reviewer Guidelines
- It's best to pull the branch locally and test it, rather than just looking at the code online!
- Check that all code is adequately covered by tests - if it isn't feel free to suggest the addition of tests.
- Always make comments, even if it's minor, or if you don't understand why something was done.

### CODE REVIEW

**Review by StevenWadeOddball — COMMENTED** [review]
@OddTomBrooks , something happened with the GIT history, it's showing you modified plan general characteristics here instead of in the last PR. Could you take a look and adjust so it shows just plan participants and providers please?

**Comment by StevenWadeOddball** [comment]
@OddTomBrooks , any updates on this?

**Comment by OddTomBrooks** [comment]
> @OddTomBrooks , any updates on this?

This was due to a 3-way merge issue and what appears to be new linter restrictions. The issue has been reconciled. The linter required me to anonymize a few unused parameters.

**Comment by OddTomBrooks** [comment]
> > @OddTomBrooks , any updates on this?
> 
> This was due to a 3-way merge issue and what appears to be new linter restrictions. The issue has been reconciled. The linter required me to anonymize a few unused parameters.

@ClayBenson94 and I had a call to discuss this. It seems related to a linter update, but there is a curious artifact in that it is not executing on main but is reproducing on the feature branch. We decided to leave the changes in this PR to address the linter issues and Clay will be opening another PR to address the linter constraints.

**Review by StevenWadeOddball — CHANGES_REQUESTED** [review]
Thanks Tom,

Overall it looks good. I smoke tested it and it worked.

The mutation for updating participants and providers should be moved to the the new file as well with extend mutation. I think that is the last piece to be updated here.

`updatePlanParticipantsAndProviders(id: UUID!, changes: PlanParticipantsAndProvidersChanges!): PlanParticipantsAndProviders!
@hasRole(role: MINT_USER)`

**Review by StevenWadeOddball — APPROVED** [review]
thanks Tom, this looks good!

**Pull request merged**
