### PR TITLE
[Easi 4345] Generic translated audit meta data, discussion reply meta data

### PR DESCRIPTION
**Pull request by StevenWadeOddball**
# EASI-4345

## Changes and Description

- Added a generic audit meta data type 
   -  All meta data to be null in the DB
   - Add a meta data type to the table
- Fill out the meta data for a discussion reply

NOTE: This meta data work will continue for additional types. PR is being created now to unblock front end work. 

## How to test this change
1. Make a discussion
2. Make a reply
3. Translate the audits
4. Verify the data is as expected.

## PR Author Review Checklist

- [ ] Met the ticket's acceptance criteria, or will meet them in a subsequent PR.
- [ ] Added or updated tests for backend resolvers or other functions as needed.
- [ ] Added or updated client tests for new components, parent components, functions, or e2e tests as necessary.
- [ ] Updated the [Postman Collection](../MINT.postman_collection.json) if necessary.

## PR Reviewer Guidelines
- It's best to pull the branch locally and test it, rather than just looking at the code online!
- Check that all code is adequately covered by tests - if it isn't feel free to suggest the addition of tests.
- Always make comments, even if it's minor, or if you don't understand why something was done.

### CODE REVIEW

**Review by patrickseguraoddball — COMMENTED** [review]
I think the `relation` in it's current state doesn't give us anything that `tableName` doesn't give us?  Not sure, but it doesn't seem like its needed at this point.  Also if we do need more specificity that `tableName` then we can probably make `relation` an enum for the type of relation.  Sorry if this doesn't make sense, maybe we can sync/async on it

**Comment by patrickseguraoddball** [comment]
Also do with think `relationContent` will always be a part of the metadata?  Can it be a part of the base type/don't need the additional union type?

**Comment by patrickseguraoddball** [comment]
Doesn't block at all, thanks for the feedback!  Yep good to go with this.

**Review by patrickseguraoddball — APPROVED** [review]

**Comment by StevenWadeOddball** [comment]
Thanks Patrick! I'll plan on doing some refactoring on this coming up and merge it for now!

**Pull request merged**
