### PR TITLE
[Feature-3495] - CR TDL Updates

### PR DESCRIPTION
**Pull request by patrickseguraoddball**
# EASI-3495

## Changes and Description

- FE Changes [(PR)](https://github.com/CMSgov/mint-app/pull/903)
- BE Changes (Directly on this feature)

## How to test this change

- This feature will mainly test the un-reviewed BE changes on this feature, and the high-level-e2e testing from a FE perspective.

### BE Migration
1. Run migrations up to the new migrations.
2. Use this SQL to insert test data
3. 
```SQL
INSERT INTO "public"."user_account"("id", "username", "is_euaid", "common_name", "locale", "email", "given_name", "family_name", "zone_info", "has_logged_in") VALUES('0e892587-a1d2-44ef-8497-6091f6d1edf1', 'MINT', 'TRUE', 'MINT Doe', 'en_US', 'MINT@local.cms.gov', 'MINT', 'Doe', 'America/Los_Angeles', 'TRUE');


/* Make Model Plan */
INSERT INTO "public"."model_plan"("id", "model_name", "archived", "status", "created_dts", "created_by") VALUES('96148eb0-7768-467b-9253-114dc032d55d', 'Excellent Model', 'FALSE', 'PLAN_DRAFT', '2024-01-23 16:14:10.491352+00', '0e892587-a1d2-44ef-8497-6091f6d1edf1');

/* Make CRTDL */

INSERT INTO "public"."plan_cr_tdl"("id", "model_plan_id", "id_number", "date_initiated", "title", "note", "created_dts", "created_by") VALUES('96148eb0-7768-467b-9253-114dc032d55d', '96148eb0-7768-467b-9253-114dc032d55d', 'asdasd', '2024-01-23 16:14:10.491352', 'asdasdasd', 'asdasdasd', '2024-01-23 16:14:10.491352+00', '0e892587-a1d2-44ef-8497-6091f6d1edf1') RETURNING "id", "model_plan_id", "id_number", "date_initiated", "title", "note", "created_dts", "modified_dts", "created_by", "modified_by";
```
4. Ensure the inserted record now exists in the plan_cr table

## PR Author Review Checklist

- [ ] Met the ticket's acceptance criteria, or will meet them in a subsequent PR.
- [ ] Added or updated tests for backend resolvers or other functions as needed.
- [ ] Added or updated client tests for new components, parent components, functions, or e2e tests as necessary.
- [ ] Updated the [Postman Collection](../MINT.postman_collection.json) if necessary.

## PR Reviewer Guidelines
- It's best to pull the branch locally and test it, rather than just looking at the code online!
- Check that all code is adequately covered by tests - if it isn't feel free to suggest the addition of tests.
- Always make comments, even if it's minor, or if you don't understand why something was done.

### CODE REVIEW

**Review by ClayBenson94 — CHANGES_REQUESTED** [review]
Changes all look good locally, but I don't think we can merge this as-is until we merge in `main` and make sure the migration #'s are updated!

**Comment by patrickseguraoddball** [comment]
I'll pull in main and make sure the migrations are correct/no conflicts

**Review by garyjzhao — DISMISSED** [review]
high level check is good.

**Review by ClayBenson94 — APPROVED** [review]

**Review by StevenWadeOddball — COMMENTED** [review]
At a high level, I was wondering why this separates CR and TDLs to separate types?

Is there any benefit to this compared with keeping them separate? (The main pro I can see is not having DateImplemented on the PlanCR Type)

I think this might be overcomplicating the solution, instead of keeping a single CR TDL type that capture both types. It feels a little misleading to have the two separate GO types, but only one table in the database.

I'd suggest it might be clearer and simpler to 
1. Keep the single Go type
2. Share SQL scripts
3. Handle the DateImplemented Field in the resolvers. (For clarity, a comment could be added to the DateImplemented field)
4. Expose the type field in the schema.

This also handles the initial request to be able to switch a TDL to a CR and vice versa.

**Comment by StevenWadeOddball** [comment]
I updated the backend to migrate existing plan_cr_tdls to crs. I also created a new TDL table, and enabled auditing.

**Comment by patrickseguraoddball** [comment]
Did a high level run after @StevenWadeOddball and all looks good!

**Review by ClayBenson94 — APPROVED** [review]
This looks good! I think the only thing to keep an eye on are the changes @StevenWadeOddball made in `pkg/worker/analyzed_audit_job.go`

We'll probably want to follow up on that deploy soon after this goes out (and potentially update the table name's Humanize function https://github.com/CMSgov/mint-app/blob/2d67a529b2be87371f0c1829195db81c9f786788/pkg/constants/constants.go#L31

**Pull request merged**
