### PR TITLE
[EASI-2370] - IT Solutions/Operational Needs FE

### PR DESCRIPTION
**Pull request by patrickseguraoddball**
# EASI-2370

## Changes and Description

- IT Solutions task list item and status tag
- IT solutions home
    - Two tables - Operational Needs, Possible Operation Needs
- Removed/replaced IT Tools from task list
- Modified the previous `ITToolsWarning` to `ITSolutionsWarning` which touched a lot of files and queries
- `HelpBox` and `NeedsStatus` components
- Unit tests

Screen Shot 2022-11-01 at 9 42 26 AM

Screen Shot 2022-11-01 at 9 42 41 AM

Screen Shot 2022-11-01 at 9 42 52 AM

## Notes
- Created one table to render both needs/solutions and possible needs
- Util functions for formatting statuses of needs, solutions as needs, and table cell formatting
- Used `/* eslint react/prop-types: 0 */` in the table to appease a weird typescript warning - TODO!
- No links on IT Solutions are functional at the moment, all return to home

## How to test this change
Best to use the postman collection to create a model plan with a needed operational need, as well as selected solutions
- Use postman to create plans with a state of:
    - no operational needs
    - one/some operational needs with no selected solutions
    - operational needs with selected solutions

## PR Author Review Checklist

- [ ] Met the ticket's acceptance criteria, or will meet them in a subsequent PR.
- [ ] Added or updated tests for backend resolvers or other functions as needed.
- [ ] Added or updated client tests for new components, parent components, functions, or e2e tests as necessary.
- [ ] Updated the [Postman Collection](../MINT.postman_collection.json) if necessary.

## PR Reviewer Guidelines
- It's best to pull the branch locally and test it, rather than just looking at the code online!
- Check that all code is adequately covered by tests - if it isn't feel free to suggest the addition of tests.
- Always make comments, even if it's minor, or if you don't understand why something was done.

### CODE REVIEW

**Comment by StevenWadeOddball** [comment]
Thanks Patrick! This looks pretty good. I noticed a few things about the display of solutions
Here I made an Operational Need, and I inserted a solution, and a possible solution

The custom solution type doesn't actually show the custom solution name from the nameOther field (it shows select a solution still
image


I also wanted to check if this table should show ones that are archived or not? I don't think it matter right now, because we are going to change that  per our sync earlier today.

**Comment by patrickseguraoddball** [comment]
> Thanks Patrick! This looks pretty good. I noticed a few things about the display of solutions Here I made an Operational Need, and I inserted a solution, and a possible solution
> 
> The custom solution type doesn't actually show the custom solution name from the nameOther field (it shows select a solution still image
> 
> I also wanted to check if this table should show ones that are archived or not? I don't think it matter right now, because we are going to change that per our sync earlier today.

Ah good catch!  I'll adjust accordingly.  As of now I don't think I was filtering on `archived`.  I can also add that in and just replace with `needed` when that change is complete, thanks Steven!

**Review by StevenWadeOddball — CHANGES_REQUESTED** [review]
Sorry Patrick! I didn't think to test this before

It looks like a custom need doesn't render correctly. I made a need with a nameOther (To Eat Ice Cream) with this GQL statement
```gql


mutation OperationalNeed{
  
  addOrUpdateCustomOperationalNeed(
      modelPlanID:"{{modelPlanID}}"
      ,customNeedType :"To eat Ice Cream"
      ,needed: true)
      {
    
        id
        modelPlanID

        name
        key
        nameOther
        needed
        # solutions
        
        createdBy
        createdDts
        modifiedBy
        modifiedDts     
    }
  }
  
```

It renders like seen below (before adding a solution)

image


However, it looks correct when you add a custom solution to it, (And a possible solution)!
image

**Comment by patrickseguraoddball** [comment]
> Sorry Patrick! I didn't think to test this before
> 
> It looks like a custom need doesn't render correctly. I made a need with a nameOther (To Eat Ice Cream) with this GQL statement
> 
> ```graphql
> mutation OperationalNeed{
>   
>   addOrUpdateCustomOperationalNeed(
>       modelPlanID:"{{modelPlanID}}"
>       ,customNeedType :"To eat Ice Cream"
>       ,needed: true)
>       {
>     
>         id
>         modelPlanID
> 
>         name
>         key
>         nameOther
>         needed
>         # solutions
>         
>         createdBy
>         createdDts
>         modifiedBy
>         modifiedDts     
>     }
>   }
>   
> ```
> 
> It renders like seen below (before adding a solution)
> 
> image
> 
> However, it looks correct when you add a custom solution to it, (And a possible solution)! image

Ah sorry, I thought I tackled them both, will do!

**Review by StevenWadeOddball — APPROVED** [review]
Thanks for working on this Patrick! 

I tested the changes, and I can see both custom needs and custom solutions!

 Note I focused on functionality for this instead of evaluating the front end code. 

image

**Review by garyjzhao — APPROVED** [review]
The FE looks good

**Pull request merged**
