### PR TITLE
EASI-3077: remove pinned buildx version

### PR DESCRIPTION
**Pull request by Jdwoodson**
# EASI-3077

## Changes and Description

- Remove pinned version of buildx to utilize latest

## How to test this change

Will include manual deploy here when complete

## PR Author Review Checklist

- [ ] Met the ticket's acceptance criteria, or will meet them in a subsequent PR.
- [ ] Added or updated tests for backend resolvers or other functions as needed.
- [ ] Added or updated client tests for new components, parent components, functions, or e2e tests as necessary.
- [ ] Updated the [Postman Collection](../MINT.postman_collection.json) if necessary.

## PR Reviewer Guidelines
- It's best to pull the branch locally and test it, rather than just looking at the code online!
- Check that all code is adequately covered by tests - if it isn't feel free to suggest the addition of tests.
- Always make comments, even if it's minor, or if you don't understand why something was done.

### CODE REVIEW

**Review by ClayBenson94 — COMMENTED** [review]
image

Should we just pin the new one for now? Either that, or we don't pin anything and just leave it on 10.4 for now

**Comment by Jdwoodson** [comment]
@ClayBenson94 

buildx-releases has been updated to include v0.11.1

now awaiting https://github.com/docker/setup-buildx-action/ to be bumped to utilize @docker/actions-toolkit 0.7.0 which contains the v0.11.1 update

**Comment by Jdwoodson** [comment]
Appears now to be waiting for https://github.com/docker/bake-action/pull/147

**Comment by Jdwoodson** [comment]
@ClayBenson94 this is ready now

**Pull request merged**
