### PR TITLE
[EASI-4218] - Readonly bug fixes

### PR DESCRIPTION
**Pull request by patrickseguraoddball**
# EASI-4218

## Changes and Description

[EASI-4219](https://jiraent.cms.gov/browse/EASI-4219)
[EASI-4221](https://jiraent.cms.gov/browse/EASI-4221)
[EASI-4222](https://jiraent.cms.gov/browse/EASI-4222)
[EASI-4223](https://jiraent.cms.gov/browse/EASI-4223)
[EASI-4224](https://jiraent.cms.gov/browse/EASI-4224)
[EASI-4225](https://jiraent.cms.gov/browse/EASI-4225)
[EASI-4226](https://jiraent.cms.gov/browse/EASI-4226)
[EASI-4229](https://jiraent.cms.gov/browse/EASI-4229)

- Addressed all findings per the above tickets

## How to test this change

Verify findings are addressed per linked images/descriptions in tickets

## PR Author Review Checklist

- [ ] Met the ticket's acceptance criteria, or will meet them in a subsequent PR.
- [ ] Added or updated tests for backend resolvers or other functions as needed.
- [ ] Added or updated client tests for new components, parent components, functions, or e2e tests as necessary.
- [ ] Updated the [Postman Collection](../MINT.postman_collection.json) if necessary.

## PR Reviewer Guidelines
- It's best to pull the branch locally and test it, rather than just looking at the code online!
- Check that all code is adequately covered by tests - if it isn't feel free to suggest the addition of tests.
- Always make comments, even if it's minor, or if you don't understand why something was done.

### CODE REVIEW

**Comment by patrickseguraoddball** [comment]
Working on the failing client tes

**Review by garyjzhao — CHANGES_REQUESTED** [review]
When adding a pay type, the payment read only page throws error in console

image

**Comment by patrickseguraoddball** [comment]
> When adding a pay type, the payment read only page throws error in console
> 
> image

Yes looking into that, I should have put it in draft

**Review by garyjzhao — APPROVED** [review]
Awesome! LGTM

**Pull request merged**
