### PR TITLE
[NOREF] Prepare for clearance statuses + GQL

### PR DESCRIPTION
**Pull request by ClayBenson94**
# NOREF

## Changes and Description

- Introduce new types and resolvers to GraphQL
  - Added `type PrepareForClearance` to the schema. This represents information helpful for rendering the "Prepare for Clearance" task list section.
    - This type has resolvers that dynamically calculate the status of the prepare for clearance section by querying multiple different data sources: The "Clearance Start Date" of the Plan Basics section, as well as the whether or not (and the last time) that each section (minus IT Tools) was marked "Ready for Clearance"
    - The logic for this happens in 2 places: [This helper function](https://github.com/CMSgov/mint-app/blob/f54678e5ff26bdf178581450c212a232fb2a160a/pkg/graph/resolvers/prepare_for_clearance.go#L33-L58) in the resolvers, and the [SQL that selects the data](https://github.com/CMSgov/mint-app/blob/a63c607496400d1f96c4e97f12302dba3cac20d6/pkg/storage/SQL/prepare_for_clearance_get_by_model_plan_id.sql)
  - Added `prepareForClearance: PrepareForClearance!` to `type ModelPlan`

## How to test this change

1. Start the app with `scripts/dev up`
2. Within the app:
  - Create a model plan
  - Query `prepareForClearance` on the model plan (should be not ready to start)
  - Modify the basics to have a clearance date within 20 days
  - Query `prepareForClearance` on the model plan (should be ready to start)
  - Update the basics to be marked ready for clearance by calling GQL to update the basics with `"status":"READY_FOR_CLEARANCE"`
  - Query `prepareForClearance` on the model plan (should be in progress)
  - Update each other section with the same update (`READY_FOR_CLEARANCE`)
  - Query `prepareForClearance` on the model plan (should be complete once all are marked ready for clearance)

## PR Author Review Checklist

- [ ] Met the ticket's acceptance criteria, or will meet them in a subsequent PR.
- [ ] Added or updated tests for backend resolvers or other functions as needed.
- [ ] Added or updated client tests for new components, parent components, functions, or e2e tests as necessary.
- [ ] Updated the [Postman Collection](../MINT.postman_collection.json) if necessary.

## PR Reviewer Guidelines
- It's best to pull the branch locally and test it, rather than just looking at the code online!
- Check that all code is adequately covered by tests - if it isn't feel free to suggest the addition of tests.
- Always make comments, even if it's minor, or if you don't understand why something was done.

### CODE REVIEW

**Review by StevenWadeOddball — APPROVED** [review]
LGTM! Thanks for making thorough Unit test for this. I think they all make sense logically. I tested locally by making a plan, seeing the status go to in progress, then updating each section to `READY_FOR_CLEARANCE` and seeing the overall status go to `READY_FOR_CLEARANCE`. I then changed the clearance start date to be beyond 20 days in the future, and saw the status change to `CANNOT_START`

**Comment by patrickseguraoddball** [comment]
I think for continuity with superficially implementing `prepareForClearance` into the task list, it makes more sense to have `latestClearanceDts` named as `modifiedDts`.  Having only `prepareForClearance` with a different name makes for more customization

**Review by patrickseguraoddball — CHANGES_REQUESTED** [review]
I think for continuity with superficially implementing `prepareForClearance` into the task list, it makes more sense to have `latestClearanceDts` named as `modifiedDts`. Having only `prepareForClearance` with a different name makes for more customization.  I requested changes, but if there's a reason to keep it with this, I can work with it.

Other than that works great, tried it out on my PFC branch and works!

**Comment by patrickseguraoddball** [comment]
Actually I could* just use a GQL alias on the query...

**Review by patrickseguraoddball — APPROVED** [review]
The alias worked fine in the case, all good!

**Pull request merged**
