### PR TITLE
[EASI-4378] Add Missing custom solution name

### PR DESCRIPTION
**Pull request by garyjzhao**
# EASI-4378

## Changes and Description

- removed conditional render of the custom solution details form as `otherHeader` in custom solution names is not in use
- code clean up

## How to test this change

1. Create a custom solution
2. Update the custom solution
3. Ensure when name of custom solution is there before you edit it
4. Verify data persist after save
5.  🎉 

## PR Author Review Checklist

- [ ] Met the ticket's acceptance criteria, or will meet them in a subsequent PR.
- [ ] Added or updated tests for backend resolvers or other functions as needed.
- [ ] Added or updated client tests for new components, parent components, functions, or e2e tests as necessary.
- [ ] Updated the [Postman Collection](../MINT.postman_collection.json) if necessary.

## PR Reviewer Guidelines
- It's best to pull the branch locally and test it, rather than just looking at the code online!
- Check that all code is adequately covered by tests - if it isn't feel free to suggest the addition of tests.
- Always make comments, even if it's minor, or if you don't understand why something was done.

### CODE REVIEW

**Review by patrickseguraoddball — CHANGES_REQUESTED** [review]
I'm getting an error when trying to add Contarctor details, when Contractor is a default solution.  I think the updated mutation variables had an effect on other types of "Other" solutions that we have. 

Screenshot 2024-06-06 at 3 43 45 PM

**Comment by patrickseguraoddball** [comment]
I think it might be worthwhile to sync, as I think there's a simpler solution that steven and I came to when we first identified this issue

**Comment by patrickseguraoddball** [comment]
Removing the solution type at the end of the url param here in both places

https://github.com/CMSgov/mint-app/blob/f65c90523197329e93ec2bbf1ceb65a7c7f2c416/src/views/ModelPlan/TaskList/ITSolutions/_components/SolutionCard/index.tsx#L242

```
<UswdsReactLink
                    className="margin-right-2 display-flex flex-align-center"
                    to={`/models/${modelID}/task-list/it-solutions/${operationalNeedID}/add-custom-solution/${
                      solution.id
                    }${
                      solution.key ? `?selectedSolution=${solution.key}` : ''
                    }`}
                  >
                    {t('updateTheseDetails')}
                    {!addingCustom && (
                      <Icon.ArrowForward className="margin-left-1" />
                    )}
                  </UswdsReactLink>

                  {addingCustom && (solution.pocName || solution.pocEmail) && (
                    <UswdsReactLink
                      className="text-red"
                      to={`/models/${modelID}/task-list/it-solutions/${operationalNeedID}/add-custom-solution/${
                        solution.id
                      }${
                        solution.key ? `?selectedSolution=${solution.key}` : ''
                      }`}
                    >
                      {t('removeTheseDetails')}
                    </UswdsReactLink>
```

**Comment by garyjzhao** [comment]
Closing in favor of #1157

**Pull request closed without merging**
