### PR TITLE
[EASI-3144] Add job code contractors

### PR DESCRIPTION
**Pull request by ClayBenson94**
# EASI-3144

## Changes and Description

- Modified existing (unused) job code config to match new job code that will be added for EUA MAC users.

## PR Author Review Checklist

- [ ] Met the ticket's acceptance criteria, or will meet them in a subsequent PR.
- [ ] Added or updated tests for backend resolvers or other functions as needed.
- [ ] Added or updated client tests for new components, parent components, functions, or e2e tests as necessary.
- [ ] Updated the [Postman Collection](../MINT.postman_collection.json) if necessary.

## PR Reviewer Guidelines
- It's best to pull the branch locally and test it, rather than just looking at the code online!
- Check that all code is adequately covered by tests - if it isn't feel free to suggest the addition of tests.
- Always make comments, even if it's minor, or if you don't understand why something was done.

### CODE REVIEW

**Review by StevenWadeOddball — CHANGES_REQUESTED** [review]
This is looking good! Something isn't resolving quite right unfortunately when I test locally. I'm not able to get the NDA when I use the new job code selection. I haven't had a chance to dig into why, but I'd be happy to take a look together tomorrow if you want!
image

**Comment by ClayBenson94** [comment]
@StevenWadeOddball I'll dig into this! Sorry for not testing a bit more and request review when I've confirmed things work locally

**Comment by ClayBenson94** [comment]
> This is looking good! Something isn't resolving quite right unfortunately when I test locally

@StevenWadeOddball Whoops - just realized I edited the EUA auth middleware (Okta) but not the local dev one! Changing that now :)

**Review by StevenWadeOddball — DISMISSED** [review]
Thanks Clay! This looks good to go :) 🚀

**Review by OddTomBrooks — DISMISSED** [review]

**Review by StevenWadeOddball — APPROVED** [review]
🚀

**Pull request merged**
