### PR TITLE
Easi 2750/create rds snapshot

### PR DESCRIPTION
**Pull request by azeez-salu**
# Easi 2750

## Changes and Description

- Updated the script to created RDS snapshot by date
- Updated pipeline to execute the script 
- I also changed the step in the pipeline where the RDS snapshot script is executed

## PR Author Review Checklist

- [ ] Met the ticket's acceptance criteria, or will meet them in a subsequent PR.
- [ ] Added or updated tests for backend resolvers or other functions as needed.
- [ ] Added or updated client tests for new components, parent components, functions, or e2e tests as necessary.
- [ ] Updated the [Postman Collection](../MINT.postman_collection.json) if necessary.

## PR Reviewer Guidelines
- It's best to pull the branch locally and test it, rather than just looking at the code online!
- Check that all code is adequately covered by tests - if it isn't feel free to suggest the addition of tests.
- Always make comments, even if it's minor, or if you don't understand why something was done.

### CODE REVIEW

**Review by StevenWadeOddball — COMMENTED** [review]
This looks good @azeez-salu! Is there anything I can do to test it? Also, is this configured anywhere to snapshot the DB on an interval? Or just before deploying?

**Comment by azeez-salu** [comment]
Thanks, @StevenWadeOddball . I tested the script locally, and it is working as intended.
This script will only create the DB snapshot before deploying. 

But we are also working on a separate task to enable automated snapshots on the RDS. That change will be on a separate PD on the mint-infra side.

**Comment by azeez-salu** [comment]
@ClayBenson94 How do we test before deploy in actions? I am curious about that as well.

**Comment by ClayBenson94** [comment]
> @ClayBenson94 How do we test before deploy in actions? I am curious about that as well.

You can always use the manual deploy job targeting this branch! This job uses the `deploy_to_environment` job, just like the main pipeline. That's probably the best way to validate that this change worked! Could always modify the code to back up in `dev`, run it, see the backup, then switch it back to `impl` and `prod` only!

**Pull request merged**
