### PR TITLE
[MINT-2990] Update PBG Filer View

### PR DESCRIPTION
**Pull request by garyjzhao**
# MINT-2990

## Description

- Add several additional items to the PBG filter view

## How to test this change

1. Filter read view to PBG's filter view
2. In Operations, evaluation, and learning, Add IDDOC support and answer `Will you produce Benefit Enhancement Files?`
2. Add all payment types (Claims based, non-claims based, and Grants)
4. Verify that the PBG filter view has all that is listed in AC

## PR Author Checklist

- [ ] I have provided a detailed description of the changes in this PR.
- [ ] I have provided clear instructions on how to test the changes in this PR.
- [ ] I have updated tests or written new tests as appropriate in this PR.
- [ ] Updated the [Postman Collection](../MINT.postman_collection.json) if necessary.

## PR Reviewer Guidelines

- It's best to pull the branch locally and test it, rather than just looking at the code online!
- When approving a PR, provide a reason _why_ you're approving it
  - e.g. "Approving because I tested it locally and all functionality works as expected"
  - e.g. "Approving because the change is simple and matches the Figma design"
- Don't be afraid to leave comments or ask questions, especially if you don't understand why something was done! (This is often a great time to suggest code comments or documentation updates)
- Check that all code is adequately covered by tests - if it isn't feel free to suggest the addition of tests.

### CODE REVIEW

**Review by patrickseguraoddball — CHANGES_REQUESTED** [review]
Missing tooltip on these questions:

Screenshot 2024-08-13 at 8 25 53 AM

Screenshot 2024-08-13 at 8 25 30 AM

Screenshot 2024-08-13 at 8 27 51 AM


I think* this question needs to be removed (it was highlighted in red in Figma).  Might want to double check with UX
Screenshot 2024-08-13 at 8 26 26 AM

Contractor is missing here Per Figma note
Screenshot 2024-08-13 at 8 28 28 AM

I think some of these may not have been documented in AC but the Figma says otherwise

**Comment by garyjzhao** [comment]
Looking through a few of the ones you've highlighted, it looks like the tooltip does not show up when its collapsed and hidden in the "questions are not application" sections. 

See below:
image
image
image

Re: red highlight -- Natasha said there's a tooltip that's showing on the question in red that should be moved to the question in blue

**Comment by garyjzhao** [comment]
RE: Contractor is missing here Per Figma note
Writing this out so that it is captured (and mostly so that I don't forget when I bring it up when @patrickseguraoddball is back in the office)


`Contractor` was already added to the filter group: 
image
and it will show up when there is a contractor added to the operational solutions:
image



Digging a bit, it looks like the `Contractor` operational solution key is not listed in `helpSolutions`.
image

Adding contractor to the help solutions results to some weirdness at other parts of the app (see below):

image

**Comment by patrickseguraoddball** [comment]
@garyjzhao Let's sync on this when you have a chance.  Contractor is not a help solution, but it is an option for an operational solution.  The two are not a 1:1.  There's a few other solutions that are selectable as operational solutions, but we don't render them in the help center as predefined solutions.  They are treated as custom solutions, where you can fill out custom information on them.

**Comment by patrickseguraoddball** [comment]
I think we probably want to get the solutions via the possible operational solutions, rather than help center solutions.  A change like this would seem to be what we might need

```
export const FilterViewSolutionsAlert = ({
  filterSolutions,
  operationalNeeds
}: {
  filterSolutions: OperationalSolutionKey[];
  operationalNeeds: any[];
}) => {
  const { t: opSolutionsMiscT } = useTranslation('opSolutionsMisc');

  const unusedSolutions = filterSolutions.filter(
    solution => !operationalNeeds.find((need: any) => need.key === solution)
  );

  const { data } = useGetPossibleOperationalSolutionsQuery();

  const helpSolutions = data?.possibleOperationalSolutions || [];

  if (unusedSolutions.length === 0) return null;

  return (
    <Alert noIcon type="info" validation>
      {opSolutionsMiscT('itSolutionsTable.unusedSolutionsAlert')}
      <ul className="margin-top-1 margin-bottom-0">
        {helpSolutions
          .filter(solution => unusedSolutions.includes(solution.key))
          .map(solution => (
            <li key={solution.key}>{solution.name}</li>
          ))}
      </ul>
    </Alert>
  );
};
```

**Review by patrickseguraoddball — APPROVED** [review]
LG

**Pull request merged**
