### PR TITLE
[EASI-3664] Drop the existing_model column from plan_general_characteristics

### PR DESCRIPTION
**Pull request by OddTomBrooks**
# EASI-3664

## Changes and Description

- Add migration dropping existing_model column

## PR Author Review Checklist

- [x] Met the ticket's acceptance criteria, or will meet them in a subsequent PR.
- [ ] Added or updated tests for backend resolvers or other functions as needed.
- [ ] Added or updated client tests for new components, parent components, functions, or e2e tests as necessary.
- [x] Updated the [Postman Collection](../MINT.postman_collection.json) if necessary.

## PR Reviewer Guidelines
- It's best to pull the branch locally and test it, rather than just looking at the code online!
- Check that all code is adequately covered by tests - if it isn't feel free to suggest the addition of tests.
- Always make comments, even if it's minor, or if you don't understand why something was done.

### CODE REVIEW

**Comment by OddTomBrooks** [comment]
Do not merge until model plan data is updated

**Review by StevenWadeOddball — CHANGES_REQUESTED** [review]
Thanks Tom, the migration works good. 

I noticed when reviewing the general characteristics postman that the `PlanGeneralCharacteristicsChanges` type hasn't been updated.
`  existingModel: String` should not be part of it anymore. Can you please update?

Also, can you update the postman query so you can just click send and it works? I get an error when trying to run it because it isn't filled out. It would be ideal if we could open the collection and send the query.

**Comment by ClayBenson94** [comment]
> Do not merge until model plan data is updated

@OddTomBrooks What remains to be updated here? Is there data in prod that needs to get updated for this, I assume?

**Comment by OddTomBrooks** [comment]
> Thanks Tom, the migration works good.
> 
> I noticed when reviewing the general characteristics postman that the `PlanGeneralCharacteristicsChanges` type hasn't been updated. ` existingModel: String` should not be part of it anymore. Can you please update?
> 
> Also, can you update the postman query so you can just click send and it works? I get an error when trying to run it because it isn't filled out. It would be ideal if we could open the collection and send the query.

Requested changes are in except turnkey click-send on the plan general characteristics update query. As discussed async, this is a design change from the existing query structure which would cause a loss of structured information by deleting various variables on the input. Such a change is outside the scope of the ticket and is best discussed as whether it's a design direction we want to take and homogenize similar queries.

**Pull request merged**
