### PR TITLE
Easi 2572/data loaders spike

### PR DESCRIPTION
**Pull request by StevenWadeOddball**
# EASI-2572

## Changes and Description

- Implement Initial Data Loaders
    - Plan Basics
    - Operational Needs
    - Operational Solutions
- [Data Loader ADR](https://github.com/CMSgov/mint-app/blob/EASI-2572/data_loaders_spike/docs/adr/0009-data-loaders.md)

## How to test this change
1. Seed Data
2. Make multiple model plans
3.  Run this query which will test all the new data loaders. If you like, you can enable debugging to verify that the database is only running 1 optimized query for each section (basics, operationalNeeds, operationalSolutions). Alternatively, you can look at the docker database logs to verify.
```gql
query modelPlanCollection {
    modelPlanCollection {
        id
        modelName
        basics{
            modelPlanID        
            id
            modelCategory
        }
        operationalNeeds {
 
            id
            modelPlanID
            name
            key
            # section
            nameOther
            needed
            solutions(includeNotNeeded:true) {
                # id
                # status
                # mustStartDts
                
                
                name
                key   
                needed
                nameOther
                pocEmail
                pocName     
                createdBy
                createdDts
            }
        }
        
    }
}
```

As this is a spike, there are still implementation details that should be added later, but the code is functional as an initial implementation. Unit tests have a basics implementation, but it would be great to more fully test them. Concurrency of is being tested using `errgroups`, as initial testing of assertions with a go routine revealed that is not a thread safe operation.

## PR Author Review Checklist

- [ ] Met the ticket's acceptance criteria, or will meet them in a subsequent PR.
- [ ] Added or updated tests for backend resolvers or other functions as needed.
- [ ] Added or updated client tests for new components, parent components, functions, or e2e tests as necessary.
- [ ] Updated the [Postman Collection](../MINT.postman_collection.json) if necessary.

## PR Reviewer Guidelines
- It's best to pull the branch locally and test it, rather than just looking at the code online!
- Check that all code is adequately covered by tests - if it isn't feel free to suggest the addition of tests.
- Always make comments, even if it's minor, or if you don't understand why something was done.

### CODE REVIEW

**Review by ClayBenson94 — CHANGES_REQUESTED** [review]
I think this is awesome that we have this functioning!

I am a bit hesitant on the amount of complexity introduced by the "JSON mapping" method vs. the "iterate over a map" method for mapping SQL results to a `[]*dataloader.Result`

Without much evidence on the performance of the two, I lean more towards the latter, keeping the SQL as simple as possible, and leaving mapping logic in the `store` methods.

@StevenWadeOddball - is this something you'd be willing to implement for Operational Solutions, and we could perhaps compare how they look, and how they perform, if we want to dive in on this problem? (Otherwise, I'd say we should probably try and keep the SQL simple and manageable)

**Comment by StevenWadeOddball** [comment]
I did some analysis, and it looks like the MappedDataLoader is actually less efficient than doing the simpler approach. As such, I'm going to switch to the simple approach. This information is in the DataLoaderBenchmarks.txt file, which I will preserve in another branch. Also reproducing here for posterity

You can reproduce the result by running only this test with this command
`go test -short -count=1 -v -p=1 github.com/cmsgov/mint-app/pkg/graph/resolvers -run  --testify.m TestBenchmarkDataLoadersComparison`

```
TestBenchmarkDataLoadersComparison Created  10  models. Num of Needs :  270
--- PASS: TestResolverSuite/TestBenchmarkDataLoadersComparison (0.75s)
    --- PASS: TestResolverSuite/TestBenchmarkDataLoadersComparison/MappedDataLoader (0.05s)
    --- PASS: TestResolverSuite/TestBenchmarkDataLoadersComparison/SimpleDataLoader (0.02s)
    --- PASS: TestResolverSuite/TestBenchmarkDataLoadersComparison/No_Data_Loader (0.33s)
    --- PASS: TestResolverSuite/TestBenchmarkDataLoadersComparison/Loader_SQL_with_Map (0.01s)
    --- PASS: TestResolverSuite/TestBenchmarkDataLoadersComparison/Loader_SQL_Simplified (0.01s)

TestBenchmarkDataLoadersComparison Created  50  models. Num of Needs :  1350
--- PASS: TestResolverSuite/TestBenchmarkDataLoadersComparison (2.81s)
    --- PASS: TestResolverSuite/TestBenchmarkDataLoadersComparison/MappedDataLoader (0.12s)
    --- PASS: TestResolverSuite/TestBenchmarkDataLoadersComparison/SimpleDataLoader (0.03s)
    --- PASS: TestResolverSuite/TestBenchmarkDataLoadersComparison/No_Data_Loader (1.13s)
    --- PASS: TestResolverSuite/TestBenchmarkDataLoadersComparison/Loader_SQL_with_Map (0.07s)
    --- PASS: TestResolverSuite/TestBenchmarkDataLoadersComparison/Loader_SQL_Simplified (0.02s)

TestBenchmarkDataLoadersComparison Created  50  models. Num of Needs :  1350
--- PASS: TestResolverSuite (2.56s)
    --- PASS: TestResolverSuite/TestBenchmarkDataLoadersComparison (2.51s)
        --- PASS: TestResolverSuite/TestBenchmarkDataLoadersComparison/MappedDataLoader (0.11s)
        --- PASS: TestResolverSuite/TestBenchmarkDataLoadersComparison/SimpleDataLoader (0.03s)
        --- PASS: TestResolverSuite/TestBenchmarkDataLoadersComparison/No_Data_Loader (0.86s)
        --- PASS: TestResolverSuite/TestBenchmarkDataLoadersComparison/Loader_SQL_with_Map (0.07s)
        --- PASS: TestResolverSuite/TestBenchmarkDataLoadersComparison/Loader_SQL_Simplified (0.01s)

TestBenchmarkDataLoadersComparison Created  100  models. Num of Needs :  2700
    --- PASS: TestResolverSuite/TestBenchmarkDataLoadersComparison (5.00s)
        --- PASS: TestResolverSuite/TestBenchmarkDataLoadersComparison/MappedDataLoader (0.15s)
        --- PASS: TestResolverSuite/TestBenchmarkDataLoadersComparison/SimpleDataLoader (0.05s)
        --- PASS: TestResolverSuite/TestBenchmarkDataLoadersComparison/No_Data_Loader (2.25s)
        --- PASS: TestResolverSuite/TestBenchmarkDataLoadersComparison/Loader_SQL_with_Map (0.13s)
        --- PASS: TestResolverSuite/TestBenchmarkDataLoadersComparison/Loader_SQL_Simplified (0.03s)


TestBenchmarkDataLoadersComparison Created  200  models. Num of Needs :  5400
    --- PASS: TestResolverSuite/TestBenchmarkDataLoadersComparison (10.75s)
        --- PASS: TestResolverSuite/TestBenchmarkDataLoadersComparison/MappedDataLoader (0.24s)
        --- PASS: TestResolverSuite/TestBenchmarkDataLoadersComparison/SimpleDataLoader (0.07s)
        --- PASS: TestResolverSuite/TestBenchmarkDataLoadersComparison/No_Data_Loader (5.15s)
        --- PASS: TestResolverSuite/TestBenchmarkDataLoadersComparison/Loader_SQL_with_Map (0.28s)
        --- PASS: TestResolverSuite/TestBenchmarkDataLoadersComparison/Loader_SQL_Simplified (0.05s)

 TestBenchmarkDataLoadersComparison Created  500  models. Num of Needs :  13500
    --- PASS: TestResolverSuite/TestBenchmarkDataLoadersComparison (32.20s)
        --- PASS: TestResolverSuite/TestBenchmarkDataLoadersComparison/MappedDataLoader (0.34s)
        --- PASS: TestResolverSuite/TestBenchmarkDataLoadersComparison/SimpleDataLoader (0.15s)
        --- PASS: TestResolverSuite/TestBenchmarkDataLoadersComparison/No_Data_Loader (14.16s)
        --- PASS: TestResolverSuite/TestBenchmarkDataLoadersComparison/Loader_SQL_with_Map (0.65s)
        --- PASS: TestResolverSuite/TestBenchmarkDataLoadersComparison/Loader_SQL_Simplified (0.14s)

TestBenchmarkDataLoadersComparison Created  1000  models. Num of Needs :  27000
    --- PASS: TestResolverSuite/TestBenchmarkDataLoadersComparison (69.73s)
        --- PASS: TestResolverSuite/TestBenchmarkDataLoadersComparison/MappedDataLoader (6.53s)
        --- PASS: TestResolverSuite/TestBenchmarkDataLoadersComparison/SimpleDataLoader (0.31s)
        --- PASS: TestResolverSuite/TestBenchmarkDataLoadersComparison/No_Data_Loader (26.41s)
        --- PASS: TestResolverSuite/TestBenchmarkDataLoadersComparison/Loader_SQL_with_Map (2.34s)
        --- PASS: TestResolverSuite/TestBenchmarkDataLoadersComparison/Loader_SQL_Simplified (0.45s)
        
 TestBenchmarkDataLoadersComparison Created  2000  models. Num of Needs :  54000
    --- FAIL: TestResolverSuite/TestBenchmarkDataLoadersComparison (113.53s)
        --- PASS: TestResolverSuite/TestBenchmarkDataLoadersComparison/MappedDataLoader (15.44s)
        --- PASS: TestResolverSuite/TestBenchmarkDataLoadersComparison/SimpleDataLoader (0.63s)
        --- FAIL: TestResolverSuite/TestBenchmarkDataLoadersComparison/No_Data_Loader (45.55s)
        --- PASS: TestResolverSuite/TestBenchmarkDataLoadersComparison/Loader_SQL_with_Map (2.76s)
        --- PASS: TestResolverSuite/TestBenchmarkDataLoadersComparison/Loader_SQL_Simplified (0.61s)        
```

**Comment by StevenWadeOddball** [comment]
@ClayBenson94 , I reverted the benchmark, I branched off of this if we want to benchmark in the future we an look back at that branch(https://github.com/CMSgov/mint-app/compare/main...EASi-2572/data_loader_benchmark), or if there is another useful place we can put this I can add it there

**Review by ClayBenson94 — APPROVED** [review]
Sorry for the long delay on this - but thank you for all the changes and updates as we've discussed this!

**Pull request merged**
