### PR TITLE
[EASI-2726] - Update Trigger Questions for Operational Needs

### PR DESCRIPTION
**Pull request by patrickseguraoddball**
# EASI-2726

## Changes and Description

- Added new op needs question warning
- Updated tests

## PR Author Review Checklist

- [ ] Met the ticket's acceptance criteria, or will meet them in a subsequent PR.
- [ ] Added or updated tests for backend resolvers or other functions as needed.
- [ ] Added or updated client tests for new components, parent components, functions, or e2e tests as necessary.
- [ ] Updated the [Postman Collection](../MINT.postman_collection.json) if necessary.

## PR Reviewer Guidelines
- It's best to pull the branch locally and test it, rather than just looking at the code online!
- Check that all code is adequately covered by tests - if it isn't feel free to suggest the addition of tests.
- Always make comments, even if it's minor, or if you don't understand why something was done.

### CODE REVIEW

**Review by garyjzhao — COMMENTED** [review]
I am not getting the scroll to element function to work.. whenever I click `Change Model Plan answer` it goes to the top of page. I am assuming it should scroll to the particular question, right?

**Comment by patrickseguraoddball** [comment]
> I am not getting the scroll to element function to work.. whenever I click `Change Model Plan answer` it goes to the top of page. I am assuming it should scroll to the particular question, right?

Ah yes you are right

**Review by garyjzhao — COMMENTED** [review]
Functional code is working expected. Failing test are simply snapshots. Will wait for rereview when @patrickseguraoddball returns from PTO

**Review by garyjzhao — APPROVED** [review]
thanks for the changes

**Pull request merged**
