### PR TITLE
Easi 1942/plan participants and providers

### PR DESCRIPTION
**Pull request by patrickseguraoddball**
# EASI-1942

## Changes and Description

- Task List section for Participants and Providers
- Query for existing models
- Cypress and unit testing

## Notes

Changed a db dumb file for cypress testing with 'Empty Plan'

Fixed an error message for document upload, and tweaked Multiselect to remove incorrect i18n usage

There are no validations on the form as none are required as far as I can tell.  This section is completely free form, no dates to validate, etc.  

The range slider is a newly utilized component from Truss, and the scale is quite large.  Small numbers won't really be visually apparent.  May need to consult with UX on this.

## How to test this change

- Create or seed a model plan
- Select `Participants and Providers` from the task list
- Try to break it on each page of the form

## PR Author Review Checklist

- [ ] Met the ticket's acceptance criteria, or will meet them in a subsequent PR.
- [ ] Added or updated tests for backend resolvers or other functions as needed.
- [ ] Added or updated client tests for new components, parent components, functions, or e2e tests as necessary.
- [ ] Tested user-facing changes with voice-over and the [rotor menu](https://support.apple.com/guide/voiceover/with-the-voiceover-rotor-mchlp2719/mac)

## PR Reviewer Guidelines
- It's best to pull the branch locally and test it, rather than just looking at the code online!
- Check that all code is adequately covered by tests - if it isn't feel free to suggest the addition of tests.
- Always make comments, even if it's minor, or if you don't understand why something was done.

### CODE REVIEW

**Comment by StevenWadeOddball** [comment]
I see what you mean about the slider having a really large scale, it does seem to not show the value as nicely as you'd hope. I wonder if there could be a number directly under the circle to represent the value as well?
 
Also, I noticed if I press enter when I'm in the number of participants text box or anywhere else on the page, it activates the next page button. Is that how you'd expect the form to work? It surprises me when I can see another form element is selected
image

**Comment by StevenWadeOddball** [comment]
Should the + add an additional note button go away after the Notes field appears?
image

**Comment by StevenWadeOddball** [comment]
I think this question on page 5 is meant to say how frequently are providers added. [See Figma](https://www.figma.com/file/M72DReE73SSXMN48WZfaKN/MINT---New-Model-Process-(Model-Intake)?node-id=387%3A42663)
image

**Comment by patrickseguraoddball** [comment]
> Should the + add an additional note button go away after the Notes field appears? image

Yeah ideally I think it should.   I think we can leave this as a part of the work for - https://jiraent.cms.gov/browse/EASI-2069

**Comment by patrickseguraoddball** [comment]
> 

From what I've read on accessibility related to this, is that it is intended, and screen readers know that pressing enter on <input type="text" /> is an implicit form submission.  It is the default behavior for the html element.  <textarea /> is not an implicit submission, and will move the carat to the next line.  I can consult with UX on this as well or if we have access to an accessibility guru here at oddball.

**Comment by patrickseguraoddball** [comment]
> > This field on page 4, communication isn't populated with the backend data consistently image
> > This is what the payload looks like. A few times it did populate when I clicked back, but most of the time it did not. If I moved forward at this point in time, it would override the data and update the database to null.
> > ```json
> > {
> >     "data": {
> >         "modelPlan": {
> >             "modelName": "Empty Plan",
> >             "participantsAndProviders": {
> >                 "id": "37cfc121-4ce4-4994-ada2-3e9b97db5791",
> >                 "modelPlanID": "53054496-6d1f-47f5-b6a0-1edaf73b935e",
> >                 "participants": [
> >                     "COMMERCIAL_PAYERS",
> >                     "CONVENER",
> >                     "OTHER"
> >                 ],
> >                 "medicareProviderType": null,
> >                 "statesEngagement": null,
> >                 "participantsOther": "aSHJKLahsk",
> >                 "participantsNote": "asd",
> >                 "participantsCurrentlyInModels": true,
> >                 "participantsCurrentlyInModelsNote": "asd",
> >                 "modelApplicationLevel": " asd",
> >                 "expectedNumberOfParticipants": 50,
> >                 "estimateConfidence": "FAIRLY",
> >                 "confidenceNote": null,
> >                 "recruitmentMethod": "OTHER",
> >                 "recruitmentOther": "asdfasd",
> >                 "recruitmentNote": "asd",
> >                 "selectionMethod": [
> >                     "APPLICATION_SUPPORT_CONTRACTOR",
> >                     "CMS_COMPONENT_OR_PROCESS",
> >                     "BASIC_CRITERIA"
> >                 ],
> >                 "selectionOther": null,
> >                 "selectionNote": "asd",
> >                 "communicationMethod": [
> >                     "OTHER",
> >                     "MASS_EMAIL"
> >                 ],
> >                 "communicationMethodOther": "Fun stuff",
> >                 "communicationNote": "asdasd",
> >                 "participantAssumeRisk": true,
> >                 "riskType": "ONE_SIDED",
> >                 "riskOther": null,
> >                 "riskNote": "asda",
> >                 "willRiskChange": false,
> >                 "willRiskChangeNote": "asd",
> >                 "coordinateWork": null,
> >                 "coordinateWorkNote": null,
> >                 "gainsharePayments": null,
> >                 "gainsharePaymentsTrack": null,
> >                 "gainsharePaymentsNote": null,
> >                 "participantsIds": [],
> >                 "participantsIdsOther": null,
> >                 "participantsIDSNote": null,
> >                 "providerAdditionFrequency": null,
> >                 "providerAdditionFrequencyOther": null,
> >                 "providerAdditionFrequencyNote": null,
> >                 "providerAddMethod": [],
> >                 "providerAddMethodOther": null,
> >                 "providerAddMethodNote": null,
> >                 "providerLeaveMethod": [],
> >                 "providerLeaveMethodOther": null,
> >                 "providerLeaveMethodNote": null,
> >                 "providerOverlap": null,
> >                 "providerOverlapHierarchy": null,
> >                 "providerOverlapNote": null,
> >                 "createdBy": "MINT",
> >                 "createdDts": "2022-06-06T13:10:45.731559Z",
> >                 "modifiedBy": "MINT",
> >                 "modifiedDts": "2022-06-22T20:33:48.25444Z",
> >                 "status": "IN_PROGRESS",
> >                 "__typename": "PlanParticipantsAndProviders"
> >             },
> >             "__typename": "ModelPlan"
> >         }
> >     }
> > }
> > ```
> 
> I loaded a seeded model and it didn't have any issue. When I looked at dev tools in the console, I did see a warning related to caching in Apollo. I have a hunch that this issue is related to that, and is also why the issue seems to be intermittent.
> 
> ```
> invariant.ts:42 Cache data may be lost when replacing the modelPlan field of a Query object.
> 
> To address this problem (which is not a bug in Apollo Client), either ensure all objects of type ModelPlan have an ID or a custom merge function, or define a custom merge function for the Query.modelPlan field, so InMemoryCache can safely merge these objects:
> 
>   existing: {"__typename":"ModelPlan","collaborators":[{"__ref":"PlanCollaborator:b49e65fd-4767-4aed-b40e-3e1e5c20be57"}]}
>   incoming: {"__typename":"ModelPlan","modelName":"Empty Plan","participantsAndProviders":{"__ref":"PlanParticipantsAndProviders:37cfc121-4ce4-4994-ada2-3e9b97db5791"}}
> 
> For more information about these options, please refer to the documentation:
> 
>   * Ensuring entity objects have IDs: https://go.apollo.dev/c/generating-unique-identifiers
>   * Defining custom merge functions: https://go.apollo.dev/c/merging-non-normalized-objects
> ```

I wasn't able to replicate this caching issue.  If you have time tomorrow, let's sync up to get some eyes on it/see if I can replicate it.  

Thanks soooo much Steven for getting quick eyes and great feedback on this PR!

**Comment by StevenWadeOddball** [comment]
> > 
> 
> From what I've read on accessibility related to this, is that it is intended, and screen readers know that pressing enter on `<input type="text" />` or `<input type="number" />` is an implicit form submission. It is the default behavior for the html element. `<textarea />` is not an implicit submission, and will move the carat to the next line. I can consult with UX on this as well or if we have access to an accessibility guru here at oddball.
> 
> As far as the range slider, I've let Natasha know, and I will demo this tomorrow for her. The text/number input below will update as slider moves/if the number is small to let the user know, so it may not be an issue

Awesome! Thanks for letting me know about the accessibility consideration behind that. I have been second guessing what normal behavior actually is, it may very well be that I have false expectations for this.

**Review by StevenWadeOddball — APPROVED** [review]
Looks great to me Patrick! Excellent job figuring out that caching issue, I wasn't able to get the issue to occur again, and I didn't see any messages in the console related to it.

**Pull request merged**
