### PR TITLE
[NOREF] Created an initial postman collection

### PR DESCRIPTION
**Pull request by ClayBenson94**
# EASI-000

## Changes and Description

- Created an initial Postman collection
- Modified PR review checklist to have updating the collection as an item

## How to test this change

1. Download [Postman](https://www.postman.com/)
2. Import the collection added in this repository
3. Start the server with `scripts/dev up:backend`
4. Attempt to use the queries in the collection!

## PR Author Review Checklist

- [x] Met the ticket's acceptance criteria, or will meet them in a subsequent PR.
- [x] Added or updated tests for backend resolvers or other functions as needed.
- [x] Added or updated client tests for new components, parent components, functions, or e2e tests as necessary.
- [x] Updated the [Postman Collection](../MINT.postman_collection.json) if necessary.

## PR Reviewer Guidelines
- It's best to pull the branch locally and test it, rather than just looking at the code online!
- Check that all code is adequately covered by tests - if it isn't feel free to suggest the addition of tests.
- Always make comments, even if it's minor, or if you don't understand why something was done.

### CODE REVIEW

**Review by rileyanderson — COMMENTED** [review]
Nice! I have a question about variables.. we don't need to add them now but would it be good to add them as we go? My thinking is if you add seeded data you should be adding that data to Postman as well. Thoughts?

**Comment by StevenWadeOddball** [comment]
> Nice! I have a question about variables.. we don't need to add them now but would it be good to add them as we go? My thinking is if you add seeded data you should be adding that data to Postman as well. Thoughts?

I like that! I think @ClayBenson94 and I had discussed using variables in Postman off seeded data before as well. Right now with this [current PR](https://github.com/CMSgov/mint-app/pull/211#discussion_r971887321), we aren't seeding a id's. That might change in the future, but in the meantime, we'd need postman to set variable programmatically. 

I haven't tried it myself, but it looks like you can set variables using the test tab and parsing a response. ( So we could query model plan and get all the child task list section ids.

I do agree that it would probably be something to iterate on rather than need to ad it all now.

**Review by StevenWadeOddball — CHANGES_REQUESTED** [review]
I think this  is a great addition. 

I noticed the currentUser is incomplete --> What I provide below should be valid

```gql
query currentUser {
    currentUser{
        launchDarkly {
            userKey
        }
    }
}
```

**Comment by StevenWadeOddball** [comment]
@ClayBenson94 & @rileyanderson have either of you used the team feature for Postman to have a shared API there? Any thoughts of doing that verses importing the api from the Repo?

**Comment by rileyanderson** [comment]
> @ClayBenson94 & @rileyanderson have either of you used the team feature for Postman to have a shared API there? Any thoughts of doing that verses importing the api from the Repo?

@StevenWadeOddball I have but it is a paid feature. I think that is what we are trying to avoid for the time being. It's nice, it has versioning that is basically just git where you can create pull requests and stuff. I think that would be the ideal solution but this is a good start I think.

**Review by OddTomBrooks — APPROVED** [review]

**Comment by ClayBenson94** [comment]
@OddTomBrooks @StevenWadeOddball @rileyanderson I just pushed up changes to add CRs and TDLs, since that made it to `main`. Re-requesting review, please!

**Review by StevenWadeOddball — APPROVED** [review]
I tested this locally and it worked well!

**Pull request merged**
