### PR TITLE
[EASI-2267] - Prepare for clearance

### PR DESCRIPTION
**Pull request by patrickseguraoddball**
# EASI-2267

## Changes and Description

- Prepare for clearance task list item
- Checklist form component
- Review (readonly) component
- Subscription lock/modal on review component
- Clearance warning/modal if already cleared
- Unit/cypress testing

Out of scope but made ticket much easier to develop
- Context provider for getting model plan info from anywhere in app

Screen Shot 2022-10-25 at 9 56 53 AM

Screen Shot 2022-10-25 at 9 57 13 AM

Screen Shot 2022-10-25 at 9 57 38 AM

Screen Shot 2022-10-25 at 9 57 57 AM

Screen Shot 2022-10-25 at 9 58 14 AM

## How to test this change

- Seed the database
- Enter into `Empty Plan` and verify the info box on `Prepare for clearance` task list section
- Enter into the `Basics` and populate the `clearanceStarts` with a date within 20 days
- Return to task list and verify `Prepare for clearance` is now `Ready`
- Enter into the task list item and check/uncheck checkboxes and update status
- Verify task list status is now `In progress`
- From the checklist, review all sections and try to edit a section that has already been cleared
- Confirm modal when trying to access cleared section
- GQL subscription lock modal will appear if another browser open and occupying task list section

## PR Author Review Checklist

- [ ] Met the ticket's acceptance criteria, or will meet them in a subsequent PR.
- [ ] Added or updated tests for backend resolvers or other functions as needed.
- [ ] Added or updated client tests for new components, parent components, functions, or e2e tests as necessary.
- [ ] Updated the [Postman Collection](../MINT.postman_collection.json) if necessary.

## PR Reviewer Guidelines
- It's best to pull the branch locally and test it, rather than just looking at the code online!
- Check that all code is adequately covered by tests - if it isn't feel free to suggest the addition of tests.
- Always make comments, even if it's minor, or if you don't understand why something was done.

### CODE REVIEW

**Comment by StevenWadeOddball** [comment]
@patrickseguraoddball This looks good! The seeded data update looks good too!

I didn't get the modal like the test script suggested when I updated a section that is marked ready for clearance, ( I tried specifically in Model Basics). When I click it, I'm brought directly to the first page to edit
image

I was also wondering if we should do anything we can do to make it clearer that you can only go back to in progress when you update a task list section from Ready for Clearance. Right now, I can get to the last page of the form with `Ready for Clearance`, and then mark that it is `ready for review`. Like we've previously talked about, the status goes directly to in progress instead of `ready for review`. Do you think this is worth bringing up with UX?

**Comment by patrickseguraoddball** [comment]
> @patrickseguraoddball This looks good! The seeded data update looks good too!
> 
> I didn't get the modal like the test script suggested when I updated a section that is marked ready for clearance

The modal should only appear on the review page, bottom link to directly edit.

**Comment by StevenWadeOddball** [comment]
> > @patrickseguraoddball This looks good! The seeded data update looks good too!
> > I didn't get the modal like the test script suggested when I updated a section that is marked ready for clearance
> > Thanks Steven!
> 
> The modal should only appear on the review page, bottom link to directly edit.
> 
> Screen Shot 2022-10-25 at 4 57 04 PM


Perfect! Thanks Patrick, that's working as expected then :) 
image

**Review by garyjzhao — APPROVED** [review]
HUGE UPDATE! Great work!

**Pull request merged**
