### PR TITLE
EASI-2257/ ADR for worker/scheduler framework 

### PR DESCRIPTION
**Pull request by rileyanderson**
# EASI-2257

## Changes and Description

- Add ADR with decision on worker/scheduler framework

## PR Author Review Checklist

- [ ] Met the ticket's acceptance criteria, or will meet them in a subsequent PR.
- [ ] Added or updated tests for backend resolvers or other functions as needed.
- [ ] Added or updated client tests for new components, parent components, functions, or e2e tests as necessary.
- [ ] Tested user-facing changes with voice-over and the [rotor menu](https://support.apple.com/guide/voiceover/with-the-voiceover-rotor-mchlp2719/mac)

## PR Reviewer Guidelines
- It's best to pull the branch locally and test it, rather than just looking at the code online!
- Check that all code is adequately covered by tests - if it isn't feel free to suggest the addition of tests.
- Always make comments, even if it's minor, or if you don't understand why something was done.

### CODE REVIEW

**Comment by StevenWadeOddball** [comment]
This is looking good! Thanks @rileyanderson! I'm curious, is there a direction you are leaning for the solution?

**Comment by rileyanderson** [comment]
> This is looking good! Thanks @rileyanderson! I'm curious, is there a direction you are leaning for the solution?

@StevenWadeOddball I am currently leaning towards Faktory. Main benefits I see are: 
- we initially won't need to add Redis (which I think we should eventually)
- Dedicated worker server
- ease of deploying server to ECS
- language agnostic (if we ever have a microservice 🤷‍♂️  we could use the same Faktory server)
- The paid features are features we would definitely use and are worth the cost imo.

Only real downside is the $199/month but I think it is worth it if we have the budget.

**Review by StevenWadeOddball — APPROVED** [review]
This sounds like a good approach to me assuming that it works within our budget! We will just need to verify that before we merge and commit to it.

**Review by ClayBenson94 — APPROVED** [review]
Thanks for making this! Super excited for us to dig into implementation!

**Pull request merged**
