### PR TITLE
[EASI-3666] FE Work for Updating Model Type Question

### PR DESCRIPTION
**Pull request by garyjzhao**
# EASI-3666

## Changes and Description

- Updated Model Type question in the basics overview page with multi-select checkboxes
- Updated Model Type question rendering in the Read Only page
- Added new `modelTypeOther` to all the queries
- Updated `modelType`'s translation mapping
- Added `modelTypeOther` to translation mapping
- Add `modelTypeOther` to csv export
- Add `modelTypeOther` to Filter group mapping
- Updated tests and snaps and mocks

## How to test this change

1. Navigate to Basic Overview task list form
2. Check that it matches the figma and is now a checkbox multi-select (instead of radio)
3. Fill out data 
4. Check to see if data presists, is recorded, shows up on Read Only and in CSV Export

## PR Author Review Checklist

- [ ] Met the ticket's acceptance criteria, or will meet them in a subsequent PR.
- [ ] Added or updated tests for backend resolvers or other functions as needed.
- [ ] Added or updated client tests for new components, parent components, functions, or e2e tests as necessary.
- [ ] Updated the [Postman Collection](../MINT.postman_collection.json) if necessary.

## PR Reviewer Guidelines
- It's best to pull the branch locally and test it, rather than just looking at the code online!
- Check that all code is adequately covered by tests - if it isn't feel free to suggest the addition of tests.
- Always make comments, even if it's minor, or if you don't understand why something was done.

### CODE REVIEW

**Comment by StevenWadeOddball** [comment]
@garyjzhao , is this targeting the right branch? It looks like there is a feature branch, a BE branch, and a FE branch. I'd imagine that this should be targeting the feature branch? 

Am I correct that this just needs review from the front end team right now?

**Comment by garyjzhao** [comment]
@StevenWadeOddball I was just about to slack you, @patrickseguraoddball and @OddTomBrooks to ask about if this PR was targetting the right branch. (But was having not-enough-coffee-monday-morning brain...)

In order to get the FE working, I had to merge Tom's BE work into my branch. So, technically, all of Tom's work is already in my PR...  So, if I target my PR to the main feature branch (`feature/EASI-3666_update_model_type_options`), then it will render Tom's PR (#862) redundant?

**Comment by StevenWadeOddball** [comment]
Thanks @garyjzhao , I'll review the BE changes in the BE branch.

**Review by patrickseguraoddball — CHANGES_REQUESTED** [review]
LG!

Only thing - the csv data isn't populated - the fields need to be added to both queries
`GetAllSingleModelData`
`GetAllModelData`

**Review by patrickseguraoddball — APPROVED** [review]
LG

**Pull request merged**
