### PR TITLE
Easi 2186/it tools warning

### PR DESCRIPTION
**Pull request by patrickseguraoddball**
# EASI-2186

## Changes and Description

- Created custom warning component for relevant IT tools questions
- Updated cypress test to utilize new warning reroute functionality
- Mobile responsiveness

Screen Shot 2022-08-15 at 2 08 30 PM

## How to test this change

- Create/open a model plan
- Ensure that IT tools status is not `READY`
- Navigate to any IT tools questions and click 'Go to question'
- Ensure the warning is displayed next to relevant question
- Ensure the link in the warning navigates back to the corresponding IT tools question

NOTE***
There a a few questions that span multiple IT tools pages, so the warning redirect may* bring you to an undesired page.  I have consulted with Natasha, and this side effect is fine.  For example 'What data do you need to monitor the model? Select all that apply.' Appears on both page 5 and 6 of IT tools.  The warning component will never have the context of the desired IT tools page (The person viewing the warning will not always be coming from IT tools, so this effect is inevitable).

## PR Author Review Checklist

- [ ] Met the ticket's acceptance criteria, or will meet them in a subsequent PR.
- [ ] Added or updated tests for backend resolvers or other functions as needed.
- [ ] Added or updated client tests for new components, parent components, functions, or e2e tests as necessary.
- [ ] Tested user-facing changes with voice-over and the [rotor menu](https://support.apple.com/guide/voiceover/with-the-voiceover-rotor-mchlp2719/mac)

## PR Reviewer Guidelines
- It's best to pull the branch locally and test it, rather than just looking at the code online!
- Check that all code is adequately covered by tests - if it isn't feel free to suggest the addition of tests.
- Always make comments, even if it's minor, or if you don't understand why something was done.

### CODE REVIEW

**Comment by ClayBenson94** [comment]
Some message!~

**Comment by ClayBenson94** [comment]
@patrickseguraoddball

**Comment by StevenWadeOddball** [comment]
@patrickseguraoddball, this is looking good so far! I had a quick question, is the warning meant to navigate you back to the page in it-tools only? Or to the page, and scroll down to the question as well?

**Comment by patrickseguraoddball** [comment]
> @patrickseguraoddball, this is looking good so far! I had a quick question, is the warning meant to navigate you back to the page in it-tools only? Or to the page, and scroll down to the question as well?

I checked with UX a week or so ago, and they said it was fine to just navigate to the IT Tools page with no scroll.  I agree I think maybe it could use one, but I left it out of the scope of this ticket

**Review by StevenWadeOddball — APPROVED** [review]
This looks good to me! I tested it locally by opening it tools and following the link to the relevant task list question, and using the link in the warning to navigate back to it-tools. 

It sent me back to the correct pages in it-tools, except in the situation that you mentioned previously (eg question spans multiple pages). Great Work!

**Pull request merged**
