### PR TITLE
[NOREF] Create "testing" environment instead of using "test"

### PR DESCRIPTION
**Pull request by ClayBenson94**
# NOREF

## Changes and Description

- Changed references that used `test` as an environment to use `testing` instead
- Created new `testing` environment in `appconfig` package to facilitate identifying when we're running tests (what used to be `test`)

We needed to have some modifications to our environment configuration because EASi historically (and currently) only had `dev`, `impl`, and `prod` environments. Therefore, an environment was created in the appconfig called `test` which was used to identify when the application was being run for local test (i.e. `go test` or `cypress`)

However, MINT has an environment literally named `test`, so the "unit testing" environment was renamed `testing`, and all instances of `test` now refer to the _deployed_ test env, rather than the "unit testing" environment.

## How to test this change

- Ensure that when `APP_ENV` is set to `test`, a real connection to CEDAR LDAP is used.
- Ensure that when `APP_ENV` is set to `testing`, the CEDAR LDAP mock is used.

## PR Author Review Checklist

- [ ] Met the ticket's acceptance criteria, or will meet them in a subsequent PR.
- [ ] Added or updated tests for backend resolvers or other functions as needed.
- [ ] Added or updated client tests for new components, parent components, functions, or e2e tests as necessary.
- [ ] Updated the [Postman Collection](../MINT.postman_collection.json) if necessary.

## PR Reviewer Guidelines
- It's best to pull the branch locally and test it, rather than just looking at the code online!
- Check that all code is adequately covered by tests - if it isn't feel free to suggest the addition of tests.
- Always make comments, even if it's minor, or if you don't understand why something was done.

### CODE REVIEW

**Comment by patrickseguraoddball** [comment]
Looks good from my end.  I only noticed one possible discrepancy - should we be including the local default for Faktory in testing as well?

https://github.com/CMSgov/mint-app/blob/45aaa6590de8cd47f16dbbc897e65813374fb136/pkg/server/routes.go#L254-L256

**Review by patrickseguraoddball — APPROVED** [review]

**Comment by rileyanderson** [comment]
> > Looks good from my end. I only noticed one possible discrepancy - should we be including the local default for Faktory in testing as well?
> > https://github.com/CMSgov/mint-app/blob/45aaa6590de8cd47f16dbbc897e65813374fb136/pkg/server/routes.go#L254-L256
> 
> @patrickseguraoddball Good callout - @rileyanderson, do you know off-hand if we have any tests that rely on Faktory? Looks like the `server_test` job succeeded, so my guess is that we don't currently have anything, but maybe some of your current work might be introducing something like that?
> 
> EDIT: Also realizing - this code was created mainly to avoid Faktory from running in deployed envs (since it was crashing the app on startup)
> 
> We might just be able to change this to something like `if !s.environment.Deployed()`, that way local execution still works as expected.

@ClayBenson94 Not yet currently. The ticket I am working on now *may* introduce it but tbh i don't think we want to run Faktory processes in our tests. We mainly just want to test the functions that Faktory will call

**Review by rileyanderson — DISMISSED** [review]

**Review by OddTomBrooks — APPROVED** [review]
LGTM

**Review by rileyanderson — CHANGES_REQUESTED** [review]
Actually, it is kinda confusing to have a `test` and `testing` env. Should we re-name the deployed one to `staging` or something? https://github.com/CMSgov/mint-app/pull/350#pullrequestreview-1213860451

**Review by rileyanderson — APPROVED** [review]

**Pull request merged**
